### ISSUE TITLE
Dependancy Vulnerabilities

### ISSUE THREAD

**Issue by andychase** [USEPA/CANARY#4]
@dbhart @kaklise @terrahaxton

I've turned on GitHub dependency checking for this repository and gave you all access.

Looks like it's still detecting some critical vulnerabilities which you can see here:

https://github.com/USEPA/CANARY/security/dependabot

I'm just letting you know!

Thank you!

**Comment by dbhart** [comment]
Thank you, I'm working on it.

**Comment by dbhart** [comment]
log4j updated to version 2.17.0, and the other dependabot alerts were addressed. Thank you!
